import '../styles/globals.css'
import "../styles/styles.scss"
import 'bootstrap/dist/css/bootstrap.min.css';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { config } from "@fortawesome/fontawesome-svg-core";
import Head from 'next/head';
import Header from './header';
import Footer from './footer';

config.autoAddCss = false;

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link type="text/css" rel="stylesheet" href="/fonts/fontsheet.css" rel="stylesheet"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Component {...pageProps} />
      <Footer></Footer>
    </div>
  )
}

export default MyApp
